#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npm test

protected_branch='prevent-main-push'
current_branch=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')

if [ $protected_branch = $current_branch ]
then
    exit 1
else
    exit 0
fi
