#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

protected_branch='main'
current_branch=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')

if [ $protected_branch = $current_branch ]
then
    echo "You cannot push to main.">&2
    exit 1
else
    exit 0
fi


npm test